# -*- coding: utf-8 -*-
"""<LucasScabelo>aop2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAjT41vzkG5cxaFXEP-q1MsQ504xwcFU
"""

aprov = 0
reprov = 0
for usu in range(1, 101):
    print('-------- Aluno:', usu,'--------')
    aop1 = float(input('Digite sua nota da AOP1(0 a 1):'))
    while aop1 < 0 or aop1 > 1:
        print("A nota deve estar entre 0 e 1.")
        aop1 = float(input('Digite sua nota da AOP1(0 a 1):'))
    aop2 = float(input('Digite sua nota da AOP2(0 a 2):'))
    while aop2 <0 or aop2 >2:
        print("A nota deve estar entre 0 e 2.")
        aop2 = float(input('Digite sua nota da AOP2(0 a 2):'))
    aop3 = float(input('Digite sua nota da AOP3(0 a 1):'))
    while aop3 <0 or aop3>1:
        print("A nota deve estar entre 0 e 1.")
        aop3 = float(input('Digite sua nota da AOP3(0 a 1):'))
    pregular = float(input('Digite sua nota da da sua prova regular(0 a 6):'))
    while pregular <0 or pregular>6:
        print("A nota deve estar entre 0 e 6.")
        pregular = float(input('Digite sua nota da da sua prova regular(0 a 6):'))
    soma =  aop1 + aop2 + aop3 + pregular
    if soma >= 7:
        print(f'Parabéns, você foi aprovado\nSua média foi de {soma}')
    else:
        precu = float(input('Digite sua nota da prova de recuperação(0 a 10):'))
        while precu<0 or precu>10:
          print("A nota deve estar entre 0 e 10.")
          precu = float(input('Digite sua nota da prova de recuperação(0 a 10):'))
        soma = (aop1 + aop2 + aop3 + pregular + precu) / 2
        if soma >= 5:
            print(f'Você foi aprovado\nsua média final: {soma}')
        else:
            print(f'Você está reprovado\nMédia final: {soma}')
    if soma >= 5:
     aprov += 1
    else:
        reprov += 1

paprov = (aprov/usu)  * 100
preprov = (reprov/usu) * 100

print(f'{paprov:.2f}% foram aprovados e {preprov:.2f}% foram reprovados')